### ISSUE TITLE
Any plans to merge jetpack compose based template?

### ISSUE THREAD

**Issue by miduch** [xmartlabs/gong#183]
Is there any plan to merge branch with jetpack compose template into master/main? 

https://github.com/xmartlabs/gong/tree/b0b617e56403c1f499704111acad89093aa3c9d6

Thanks!

**Comment by mirland** [comment]
Yes, we're currently working on the documentation, #172, after that we will merge the compose branch (main-v2)  into the master branch. However, it's ready to use, the only thing that is missing is the documentation. If you want to try it, you can execute:
```
bash <(curl -s https://raw.githubusercontent.com/xmartlabs/gong/main-v2/gong_setup.sh) main-v2
```

**Comment by miduch** [comment]
Thanks! i'll try it :)

Btw shouldn't this line 
val MAIN_DISPATCHER = StringQualifier("DEFAULT_DISPATCHER")

be 
val MAIN_DISPATCHER = StringQualifier("MAIN_DISPATCHER") instead? 


https://github.com/xmartlabs/gong/blob/b0b617e56403c1f499704111acad89093aa3c9d6/app/src/main/java/com/xmartlabs/gong/device/di/DispatchersDiModule.kt

**Comment by mirland** [comment]
Yes! you are right! Thanks for reporting the issue
