### ISSUE TITLE
Statusbar color /  insets in jetpack compose (main-v2)

### ISSUE THREAD

**Issue by miduch** [xmartlabs/gong#185]
Status bar color should be set for app theme ?

https://google.github.io/accompanist/systemuicontroller/

```
// Remember a SystemUiController
val systemUiController = rememberSystemUiController()
val useDarkIcons = MaterialTheme.colors.isLight

SideEffect {
    // Update all of the system bar colors to be transparent, and use
    // dark icons if we're in light theme
    systemUiController.setSystemBarsColor(
        color = Color.Transparent,
        darkIcons = useDarkIcons
    )

    // setStatusBarsColor() and setNavigationBarsColor() also exist
}
```

And maybe its worth consideing insets/insets-ui apis in template? 

https://google.github.io/accompanist/insets/#inset-aware-layouts-insets-ui
https://google.github.io/accompanist/insets/

https://google.github.io/accompanist/api/insets-ui/insets-ui/com.google.accompanist.insets.ui/

Thanks!

**Comment by f7deleon** [comment]
Even though this solves the problem is not consistent with how we define dependencies. we are migrating our dependencies to catalog #171 until today build script was not supported when we update that we can try if that solves the issue.

**Comment by mirland** [comment]
It was added in #202
