### ISSUE TITLE
Signin error toast not shown in jetpack compose (main-v2)

### ISSUE THREAD

**Issue by miduch** [xmartlabs/gong#187]
Signin error toast not shown in jetpack compose,  intentionally been trying to put invalid username/pwd but toast never appears on screen

```
private fun showSignInError(throwable: Throwable, context: Context) {
  if (throwable is SecurityException) {
    // In a real project, the string should be defined as a string resource.
    Toast.makeText(
        context,
        "password or username is wrong, try with userId = 'xmartlabs', password 'xmartlabs'",
        Toast.LENGTH_SHORT
    ).show()
  }
}
```

**Comment by mirland** [comment]
Which android version are you using? I could not reproduce the issue.

https://user-images.githubusercontent.com/8472881/127497122-bf995e3c-8ad5-4764-94fa-9b81159fbe74.mp4

**Comment by miduch** [comment]
Pixel 4 api 30 emulator

versions.compose = "1.0.0-beta08" // // also tried with stable 1.0.0
versions.composeMaterial = "1.0.0-beta08" // also tried with stable 1.0.0

https://user-images.githubusercontent.com/22243296/127734068-829f55f9-6df9-4832-9845-cceb74f86558.mp4

**Comment by mirland** [comment]
I could reproduce it in an emulator Pixel 4 API 30, but if I test it in a pixel 3a API 30 it works fine.

After that, I added `Toast.makeText(this, "Test", Toast.LENGTH_LONG).show()` in the [Application's oncreate method](https://github.com/xmartlabs/gong/blob/b9f4dd492e48be2f625887b1ec848bbab0a67e94/app/src/main/java/com/xmartlabs/gong/AppBase.kt#L16) and I found it's not displaying a toast, so I'm thinking it's something related with that emulator itself.

Then, I tested in one real device using API 30 and I could not reproduce.
Could you test it in a real device?

**Comment by miduch** [comment]
works fine on pixel 4a with android 12 beta
